export const anggota = [
    {
        id: 1,
        name: "Maulana",
        divisi: "UI/UX",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 2,
        name: "Angger",
        divisi: "UI/UX",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 3,
        name: "Frisca",
        divisi: "UI/UX",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 4,
        name: "Fandi",
        divisi: "UI/UX",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 5,
        name: "Muchlis",
        divisi: "UI/UX",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 6,
        name: "Catur",
        divisi: "Web Development",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 7,
        name: "Dita",
        divisi: "Web Development",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 8,
        name: "Sofiyah",
        divisi: "Web Development",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
    {
        id: 9,
        name: "Muchlis",
        divisi: "Web Development",
        img: "./images/team-1.jpg",
        linkedin: "link.com",
        git: "link.com",
        ig: "link.com",
    },
];
